title: 小英的故事
description: 蔡燦得：小英的故事
time: Mon, 25 Mar 2024 09:00:55 +0000
items:
  - title: 01. 遙遠的旅程，出發吧！
    size: 13814961
    duration: 863
  - title: 02. 旅途中處處驚險
    size: 13144425
    duration: 821
  - title: 03. 兩個媽媽和馬戲團少年
    size: 13734897
    duration: 858
  - title: 04. 另一個旅行照相館
    size: 12833343
    duration: 801
  - title: 05. 馬賽爾，暫別了！
    size: 12809157
    duration: 800
  - title: 06. 法國到了，媽媽卻病倒了！
    size: 11995173
    duration: 749
  - title: 07. 永別了，親愛的媽媽！
    size: 13814961
    duration: 863
  - title: 08. 踏上一個人的旅程
    size: 11644059
    duration: 727
  - title: 09. 終於到達馬羅克爾
    size: 13335828
    duration: 833
  - title: 10. 到工廠去工作
    size: 15323250
    duration: 957
  - title: 11. 不用推推車了
    size: 15108078
    duration: 943
  - title: 12. 壞心眼的廠長和表叔
    size: 13463847
    duration: 841
  - title: 13. 翻譯、秘書、馬伕
    size: 13910871
    duration: 869
  - title: 14. 費魯得神父的來信
    size: 12809157
    duration: 800
  - title: 15. 令人悲傷的真相
    size: 13535571
    duration: 845
  - title: 16. 親愛的爺爺，我是小英
    size: 14804502
    duration: 924
